import logging
import json
import re
import asyncio
from typing import Tuple, List, Optional
from app.config import settings
from openai import OpenAI
import httpx

logger = logging.getLogger(__name__)

def is_valid_cpt_code(code: str) -> bool:
    """Validate if a code is a valid CPT or HCPCS code."""
    if not code: return False
    code_str = str(code).strip()
    if "-" in code_str: code_str = code_str.split("-")[0].strip()
    code_str = code_str.replace(" ", "").replace(".", "").replace("/", "")
    if not code_str: return False
    if len(code_str) < 4 or len(code_str) > 5: return False
    if not code_str.isalnum(): return False
    if len(code_str) == 5:
        if code_str.isdigit(): return True
        if code_str[0].isalpha() and code_str[1:].isdigit(): return True
        if len(code_str) >= 2 and code_str[0:2].isalpha() and code_str[2:].isdigit(): return True
    if len(code_str) == 4:
        if code_str[0].isalpha() and code_str[1:].isdigit(): return True
    return False

def create_openai_client():
    """Create OpenAI client for GPT API calls"""
    if not settings.OPENAI_API_KEY:
        raise Exception("OpenAI API key not configured")
    http_client = httpx.Client(timeout=120.0, limits=httpx.Limits(max_keepalive_connections=5, max_connections=10))
    return OpenAI(api_key=settings.OPENAI_API_KEY, max_retries=2, timeout=120.0, http_client=http_client)

async def generate_cpt_with_ai(procedure_description: str, openai_client=None) -> Tuple[Optional[str], List[str]]:
    """
    Use AI (GPT-5.1) to GENERATE comprehensive CPT/HCPCS codes dynamically.
    NO static code lists - all codes are generated by AI based on procedure/service description.
    Returns (primary_cpt, supportive_cpts_list) or (None, []) if unable to generate.
    """
    if not procedure_description or not procedure_description.strip():
        return (None, [])
    
    if not openai_client:
        try:
            openai_client = create_openai_client()
        except Exception:
            return (None, [])
    
    try:
        system_prompt = """You are a medical coding expert specializing in CPT and HCPCS codes for orthopedic procedures, surgeries, and services.

🔴 CRITICAL: Generate ALL applicable CPT (5-digit numeric) AND HCPCS (Letter + 4 digits) codes.
🔴 CRITICAL: Generate codes for ALL ordered services: Surgeries, Injections, Imaging, Therapy (PT/OT), DME, Supplies, etc.
🔴 CRITICAL: You MUST GENERATE ALL POSSIBLE CODES for Workers' Compensation RFA authorization.
🔴 DO NOT extract only what is mentioned - GENERATE ALL POSSIBLE codes that could apply for the procedure/service.
🔴 Your goal is MAXIMUM code inclusion for comprehensive authorization coverage.

Your task is to GENERATE COMPREHENSIVE CODING for the PROCEDURE/SERVICE mentioned in the transcription.

🔴 CRITICAL VALIDATION RULES - 100% VALID CODES ONLY:
YOU MUST GENERATE ONLY VALID CPT OR HCPCS CODES - NO INVALID CODES ALLOWED

VALID CODE FORMATS (ONLY THESE ARE ACCEPTED):
1. CPT Codes: Exactly 5 digits, numeric only (e.g., 29881, 20610, 97110, 73721)
2. HCPCS Codes: Single letter followed by 4 digits (e.g., L1832, E0114, J1040, A4566)
   - Range: A0000-V9999
   - Common prefixes: L (DME), E (DME), J (Drugs), A (Supplies), C (Implants)

INVALID CODE FORMATS (DO NOT GENERATE THESE):
❌ Codes with 3 digits or less (e.g., 298, 88)
❌ Codes with 6+ digits (e.g., 298881, 123456)
❌ Codes with special characters (e.g., 298-81, 298.81) - except modifiers like -RT, -LT
❌ Placeholder codes (e.g., "XXXXX", "CODE", "TBD")

CRITICAL RULES - GENERATE ALL POSSIBLE VALID CODES:
1. Identify the PROCEDURE/SERVICE mentioned in the transcription (Surgery, Injection, DME, PT, MRI, etc.)
2. Generate the PRIMARY code for the main service (MUST BE VALID FORMAT)
3. Generate ALL SUPPORTIVE codes that could apply (ALL MUST BE VALID FORMAT):
   - Surgical procedures: Surgical CPTs, Implants (C/L codes), Grafts, Supplies
   - Injections: Injection CPTs, Drug HCPCS (J-codes), Guidance (7xxxx), Supplies
   - DME: Product HCPCS (L/E codes), Adjustment/Fitting codes
   - PT/OT: Evaluation (9716x), Therapeutic specific codes (97110, 97140, etc.)
   - Imaging: Primary CPT (7xxxx)
4. MANDATORY: Generate ALL POSSIBLE codes for the service
5. MANDATORY: EVERY CODE MUST BE VALID FORMAT - verify before including
6. Think comprehensively - include ALL codes that could be part of the authorization
7. DO NOT limit yourself - generate ALL possible codes
8. DO NOT stop at 6-8 codes - continue until you have ALL possible codes

Return a JSON object with:
{
  "primary_cpt": "CODE" or null,
  "supportive_cpts": ["CODE1", "CODE2", "CODE3", ...] (ALL possible comprehensive codes generated by AI),
  "description": "Brief description"
}

🔴 CRITICAL: Generate ALL possible codes dynamically using your medical coding knowledge.
🔴 DO NOT use static code lists - generate codes based on the procedure/service described.
🔴 Use GPT-5.1's comprehensive medical coding knowledge to generate all applicable codes.

If no procedure is mentioned, return:
{
  "primary_cpt": null,
  "supportive_cpts": [],
  "description": null
}"""

        user_prompt = f"""Generate COMPREHENSIVE CPT/HCPCS codes for this procedure/service:

{procedure_description}

🔴 CRITICAL - GENERATE ALL POSSIBLE VALID CODES:
🔴 100% VALID CODES REQUIRED - NO INVALID CODES ALLOWED
🔴 INCLUDE HCPCS CODES (DME, Drugs, Supplies) IF APPLICABLE

VALID CODE FORMATS (ONLY GENERATE THESE):
✓ CPT Codes: Exactly 5 digits, numeric only (e.g., 29881, 97110)
✓ HCPCS Codes: Letter + 4 digits (e.g., L1832, J1040)

INVALID FORMATS (DO NOT GENERATE):
✗ Codes with wrong length (3 digits, 6+ digits)
✗ Codes with letters in wrong position (unless valid HCPCS)
✗ Codes with special characters
✗ Placeholder codes

VALIDATION CHECKLIST - Before including each code:
□ Is it exactly 5 digits numeric OR Letter+4 digits?
□ Is it a real, valid CPT or HCPCS code?
□ If NO to any → DO NOT include that code

- FIRST: Identify the procedure/service (Surgery, Injection, DME, PT, etc.)
- Generate the PRIMARY code
- Generate ALL SUPPORTIVE codes (Surgical, Implants, Grafts, Drugs, Supplies, DME, Therapy)
- MANDATORY: Generate ALL POSSIBLE codes
- MANDATORY: EVERY CODE MUST BE VALID - verify format before including
- Think comprehensively - include ALL codes that could be part of the authorization
- DO NOT limit yourself - generate ALL possible codes
- DO NOT stop at 6-8 codes - continue until you have ALL possible codes
- FINAL CHECK: Verify ALL codes are valid format before returning

**CODE GENERATION CHECKLIST:**
For Surgery: Primary CPT, Related CPTs, Implants (C/L), Grafts, Supplies (A/Q), DME (L/E)
For Injections: Injection CPT, Drug J-codes, Guidance CPT, Supplies
For DME: Base L-code, Add-on L-codes
For PT/OT: Eval codes, Treatment codes (97xxx)
For Imaging: MRI/CT/X-ray CPTs

Return the JSON object with ALL possible comprehensive codes."""

        response = openai_client.chat.completions.create(
            model='gpt-5.1',
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ],
            temperature=0.2,
            response_format={"type": "json_object"},
            max_completion_tokens=8000
        )
        
        result = response.choices[0].message.content
        data = json.loads(result)
        
        primary = data.get("primary_cpt")
        supportive = data.get("supportive_cpts", [])
        
        validated_primary = None
        if primary:
            primary_str = str(primary).strip()
            if is_valid_cpt_code(primary_str):
                validated_primary = primary_str
        
        validated_supportive = []
        if isinstance(supportive, list):
            for code in supportive:
                if code:
                    code_str = str(code).strip()
                    if is_valid_cpt_code(code_str):
                        if code_str not in validated_supportive:
                            validated_supportive.append(code_str)
        
        return (validated_primary, validated_supportive)
    except Exception as e:
        logger.warning(f"Error generating CPT code with AI: {e}")
        return (None, [])

async def validate_cpt_codes_relevance(cpt_codes: list, transcription: str, openai_client=None) -> list:
    """Validate that CPT codes are actually relevant to the transcription."""
    if not cpt_codes or not transcription:
        return []
    
    if not openai_client:
        try:
            openai_client = create_openai_client()
        except Exception:
            return cpt_codes
    
    try:
        transcription_snippet = str(transcription)[:3000]
        system_prompt = """You are a medical coding validation expert. Your task is to validate if CPT/HCPCS codes are relevant to the procedures/services mentioned in a medical transcription.

🔴 CRITICAL: For Workers' Compensation RFA, comprehensive code inclusion is standard practice.
🔴 BE PERMISSIVE - Include codes that could reasonably apply to the procedure/service.

CRITICAL VALIDATION RULES - BE PERMISSIVE FOR RFA AUTHORIZATION:
1. FIRST: Identify the PRIMARY PROCEDURE/SERVICE from the transcription (e.g., "ACL reconstruction", "knee surgery", "injection", "MRI", "PT", "brace", etc.)

2. A code is RELEVANT if ANY of the following are true:
   - The procedure/service it represents is mentioned in the transcription
   - The code is for a related procedure/service that could be part of the authorization
   - The code is for the same body part as the procedure (e.g., knee procedure → knee codes are relevant)
   - The code is for standard components of the procedure (e.g., surgery → surgical codes, graft codes, DME codes, PT codes, supply codes)
   - The code is for DME/supplies that could be needed for the procedure
   - The code is for imaging that could be needed for the procedure
   - The code is for post-operative care related to the procedure

3. A code is NOT RELEVANT ONLY if:
   - The code is for a completely unrelated body part (e.g., knee procedure → shoulder codes are NOT relevant)
   - The code is for a completely unrelated condition (e.g., ACL surgery → rotator cuff codes are NOT relevant)
   - The code is clearly not part of the procedure/service mentioned

4. Be PERMISSIVE - mark codes as relevant if they:
   - Could reasonably be part of the procedure/service
   - Are for the same body part
   - Are standard components of the procedure type
   - Could be needed for authorization

Return a JSON object with:
{
  "relevant_codes": ["CODE1", "CODE2", ...] (only codes that are actually relevant),
  "irrelevant_codes": ["CODE3", "CODE4", ...] (codes that are not relevant)
}"""

        user_prompt = f"""Validate if these CPT/HCPCS codes are relevant to the procedure/service mentioned in this transcription:

CPT Codes to validate:
{', '.join(cpt_codes[:100])}

Transcription:
{transcription_snippet}

🔴 CRITICAL - BE PERMISSIVE FOR RFA AUTHORIZATION:
FIRST: Identify the PRIMARY PROCEDURE/SERVICE from the transcription (e.g., "ACL reconstruction", "knee surgery", "injection", "MRI", "PT", "brace", etc.)

For EACH code, verify:
1. Is this code for the same body part as the procedure? (e.g., knee procedure → knee codes are relevant)
2. Is this code a standard component of this procedure type? (e.g., surgery → surgical codes, graft codes, DME codes are relevant)
3. Could this code be needed for authorization of this procedure? (e.g., surgery → post-op DME, PT, supplies are relevant)
4. If ANY answer is YES, mark the code as RELEVANT

- Mark codes as relevant if they:
  * Are for the same body part as the procedure
  * Are standard components of the procedure type
  * Could reasonably be part of the authorization
  * Are for related services (DME, PT, imaging, supplies) that could be needed
- **CRITICAL:** DO NOT include imaging codes (MRI, X-ray, CT, etc.) unless they are explicitly mentioned as being ordered or needed in the transcription.
- **CRITICAL:** Mentions of imaging results (e.g., "MRI shows tear") are NOT orders and should NOT result in inclusion of imaging CPT codes.

Return the JSON object with relevant and irrelevant codes. Be permissive - include most codes that could apply."""

        response = openai_client.chat.completions.create(
            model='gpt-5.1',
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ],
            temperature=0.2,
            response_format={"type": "json_object"}
        )
        
        result = response.choices[0].message.content
        data = json.loads(result)
        relevant_codes = data.get("relevant_codes", [])
        return [code for code in relevant_codes if is_valid_cpt_code(str(code)) and str(code).strip() in cpt_codes]
    except Exception as e:
        logger.warning(f"Error validating CPT codes relevance: {e}")
        return cpt_codes

# =================================================================================================
# Text-based CPT Validation Functions (Ported from Monolithic Backend)
# These functions clean up the actual SOAP note text to ensure only valid codes exist in the output
# =================================================================================================

def aggressive_validate_rfa_supportive_cpts(soap_note: str) -> str:
    """
    Aggressively validate RFA Supportive CPTs section to ensure 100% valid codes.
    This function specifically targets the RFA Supportive CPTs section and validates every code.
    """
    if not soap_note:
        return soap_note
    
    result = soap_note
    invalid_codes_removed = []
    valid_codes_kept = []
    
    # Find RFA Supportive CPTs section
    rfa_supportive_pattern = r'(Supportive CPTs:\s*)(.*?)(?=\n\n|\nJustification:|$)'
    match = re.search(rfa_supportive_pattern, result, re.DOTALL | re.IGNORECASE)
    
    if not match:
        return result  # No RFA section found
    
    supportive_section = match.group(2)
    original_section = supportive_section
    
    code_pattern = r'\b([A-Z][A-Z0-9]{3,4}|[0-9]{5})\b'
    
    # Extract all codes from the section
    all_codes = re.findall(code_pattern, supportive_section, re.IGNORECASE)
    
    # Validate each code and track invalid ones
    invalid_codes_set = set()
    for code in all_codes:
        code_upper = code.upper()
        if not is_valid_cpt_code(code_upper):
            invalid_codes_set.add(code_upper)
            invalid_codes_removed.append(code_upper)
        else:
            valid_codes_kept.append(code_upper)
    
    # Remove lines containing invalid codes
    lines = supportive_section.split('\n')
    validated_lines = []
    
    for line in lines:
        # Check if line contains any invalid codes
        line_has_invalid = False
        line_codes = re.findall(code_pattern, line, re.IGNORECASE)
        
        for code in line_codes:
            if code.upper() in invalid_codes_set:
                line_has_invalid = True
                break
        
        if line_has_invalid:
            # Try to clean the line - remove invalid codes but keep the line structure
            cleaned_line = line
            for invalid_code in invalid_codes_set:
                # Remove invalid code from line (case insensitive)
                cleaned_line = re.sub(rf'\b{re.escape(invalid_code)}\b', '', cleaned_line, flags=re.IGNORECASE)
            # Clean up extra spaces
            cleaned_line = re.sub(r'\s+', ' ', cleaned_line).strip()
            # Only keep line if it still has content and isn't just punctuation
            if cleaned_line and (cleaned_line.startswith('•') or any(c.upper() not in invalid_codes_set for c in re.findall(code_pattern, cleaned_line, re.IGNORECASE))):
                validated_lines.append(cleaned_line)
        else:
            # Line is valid, keep it
            validated_lines.append(line)
    
    # Rebuild the section
    new_supportive_section = '\n'.join(validated_lines)
    
    if new_supportive_section != original_section:
        result = result[:match.start(2)] + new_supportive_section + result[match.end(2):]
        if invalid_codes_removed:
            logger.info(f"✅ Aggressive RFA Validation: Kept {len(valid_codes_kept)} valid, removed {len(invalid_codes_removed)} invalid")
    
    return result

def validate_all_cpt_codes_in_soap(soap_note: str) -> str:
    """
    Comprehensive validation of all CPT codes in SOAP note.
    Removes all invalid CPT codes and keeps only valid ones.
    """
    if not soap_note:
        return soap_note
    
    result = soap_note
    invalid_codes_removed = []
    
    # Target specific CPT code sections
    cpt_sections = [
        (r'(Primary Procedure:\s*)(.*?)(?=\n|$)', 'Primary Procedure'),
        (r'(Supportive CPTs:\s*)(.*?)(?=\n\n|\n[A-Z]|$)', 'Supportive CPTs'),
        (r'(Primary CPT:\s*)(.*?)(?=\n|$)', 'RFA Primary CPT'),
        (r'(Supportive CPTs:\s*)(.*?)(?=\n\n|\nJustification:|$)', 'RFA Supportive CPTs'),
        (r'(E/M Code:\s*)(.*?)(?=\n|$)', 'E/M Code'),
    ]
    
    for pattern, section_name in cpt_sections:
        matches = list(re.finditer(pattern, result, re.MULTILINE | re.DOTALL | re.IGNORECASE))
        for match in reversed(matches):  # Reverse to maintain positions
            section_content = match.group(2)
            original_content = section_content
            
            # Find all potential CPT codes - STRICT Pattern
            code_pattern = r'\\b((?:[A-Z][A-Z0-9]{3,4})|(?:[0-9]{5}))\\b'
            
            def validate_and_replace_code(code_match):
                code = code_match.group(1).upper()
                if is_valid_cpt_code(code):
                    return code_match.group(0)  # Keep valid code
                else:
                    invalid_codes_removed.append(code)
                    return ""  # Remove invalid code
            
            # Validate all codes in this section
            validated_content = re.sub(code_pattern, validate_and_replace_code, section_content, flags=re.IGNORECASE)
            
            # Clean up
            validated_content = re.sub(r'\n\s*\n+', '\n', validated_content)
            validated_content = re.sub(r'[ \t]+', ' ', validated_content)
            validated_content = validated_content.strip()
            
            if validated_content != original_content:
                result = result[:match.start(2)] + validated_content + result[match.end(2):]
    
    # Also validate codes in bulleted lists
    bullet_pattern = r'(•\s*)([A-Z0-9]{4,5})\s*[—\-:]\s*([^\n]+)'
    def validate_bullet_code(bullet_match):
        code = bullet_match.group(2).upper()
        if is_valid_cpt_code(code):
            return bullet_match.group(0)
        else:
            invalid_codes_removed.append(code)
            return ""
    
    result = re.sub(bullet_pattern, validate_bullet_code, result, flags=re.IGNORECASE | re.MULTILINE)
    
    # Final cleanup
    result = re.sub(r'\n\s*\n\s*\n+', '\n\n', result)
    result = re.sub(r'[ \t]{2,}', ' ', result)
    
    if invalid_codes_removed:
        logger.info(f"✅ Text CPT Validation: Removed {len(invalid_codes_removed)} invalid codes.")
        
    return result

def extract_and_validate_cpt_codes_from_soap(soap_note: str) -> str:
    """Wrapper that applies all validation logic to a SOAP note"""
    if not soap_note: return soap_note
    
    # First pass: General validation
    note = validate_all_cpt_codes_in_soap(soap_note)
    
    # Second pass: Aggressive RFA section validation
    note = aggressive_validate_rfa_supportive_cpts(note)
    
    return note

# =================================================================================================
# Advanced AI CPT Generation & Correction (Ported from Monolithic Backend)
# =================================================================================================

async def validate_and_correct_cpt_codes(soap_note: str, transcription: str, openai_client) -> str:
    """
    Post-process SOAP note to validate and correct CPT codes.
    Uses AI to generate CPT codes for procedures not in the mapping, making the system unlimited.
    Replaces "Not documented" with actual CPT codes when procedures are mentioned.
    Also validates and removes invalid CPT codes.
    """
    if not soap_note or not transcription:
        return soap_note
    
    result = soap_note
    
    # Extract procedures/treatments from transcription
    transcription_lower = transcription.lower()
    
    # Check for common procedure keywords
    procedure_keywords = [
        "injection", "physical therapy", "pt", "mri", "x-ray", "xray", "ct scan",
        "walking boot", "cam boot", "brace", "crutches", "walker", "cane",
        "surgery", "arthroscopy", "epidural", "facet", "trigger point",
        "therapy", "imaging", "procedure", "surgery"
    ]
    
    has_procedures = any(keyword in transcription_lower for keyword in procedure_keywords)
    
    if not has_procedures:
        return soap_note  # No procedures mentioned, no need to correct
    
    # Pattern to find CPT sections with "Not documented"
    cpt_patterns = [
        # Primary Procedure
        (r'(Primary Procedure:\s*\[)(Not documented|\[Not documented\])(\]\s*—\s*\[Procedure Name\])', 
         _generate_cpt_for_procedure),
        # Supportive CPTs
        (r'(Supportive CPTs:\s*\[)(Not documented|\[Not documented\])(\])',
         _generate_supportive_cpts),
        # RFA Primary CPT
        (r'(Primary CPT:\s*\[)(Not documented|\[Not documented\]|Code)(\])',
         _generate_cpt_for_rfa),
        # RFA Supportive CPTs
        (r'(Supportive CPTs:\s*\[)(Not documented|\[Not documented\]|Codes)(\])',
         _generate_supportive_cpts_rfa),
    ]
    
    # Collect all matches and their corresponding generator functions
    tasks_to_run = []
    
    # We use a unique marker for each replacement to avoid issues with .replace()
    # when multiple placeholders have the same text
    placeholder_map = {}
    
    for pattern, generator_func in cpt_patterns:
        matches = list(re.finditer(pattern, result, re.IGNORECASE | re.MULTILINE))
        for i, match in enumerate(matches):
            match_text = match.group(0)
            # Create a unique marker for this specific match instance
            marker = f"__CPT_MARKER_{len(tasks_to_run)}__"
            # Replace only the FIRST occurrence of match_text with marker
            # this works because we iterate in order
            result = result.replace(match_text, marker, 1)
            
            # Prepare the parallel task
            tasks_to_run.append(
                asyncio.to_thread(generator_func, transcription, openai_client, match)
            )
            placeholder_map[marker] = None
    
    if tasks_to_run:
        logger.info(f"🚀 Starting parallel CPT generation for {len(tasks_to_run)} items...")
        replacements = await asyncio.gather(*tasks_to_run)
        
        # Map markers back to their generated results
        for i, marker in enumerate(placeholder_map.keys()):
            replacement = replacements[i]
            # Replace the marker with the actual generated CPT text
            result = result.replace(marker, replacement)
            
        logger.info(f"✅ Parallel CPT generation complete")
    
    # CRITICAL: Validate and remove ALL invalid CPT codes before returning
    result = validate_all_cpt_codes_in_soap(result)
    
    return result


def _generate_cpt_for_procedure(transcription: str, openai_client, match) -> str:
    """Generate CPT code for a procedure mentioned in transcription - fully AI-driven"""
    # Try to extract procedure name from context
    procedure_text = _extract_procedure_from_transcription(transcription)
    
    if procedure_text and openai_client:
        # NOTE: This creates a NEW asyncio loop if not careful, but generate_cpt_with_ai is async.
        # But we called this via asyncio.to_thread, which runs in a thread.
        # generate_cpt_with_ai is ASYNC. We can't call await in a sync function run in a thread easily for the same loop.
        # However, generate_cpt_with_ai uses openai_client.chat.completions.create which is SYNCHRONOUS in the provided code above?
        # Let's check generate_cpt_with_ai definition.
        # It calls: response = openai_client.chat.completions.create(...) -> SYNC call because OpenAI client is created with httpx.Client (Sync).
        # Wait, create_openai_client returns OpenAI(... http_client=httpx.Client(...)) -> Sync Client.
        # So openai_client.chat.completions.create is blocking.
        # BUT generate_cpt_with_ai is defined as `async def`.
        # So we must `await` it.
        # If _generate_cpt_for_procedure is synchronous (called by to_thread), it cannot await validly without a loop.
        
        # FIX: The original code used `asyncio.to_thread` on `generator_func`.
        # The `generator_func` in original code are `_generate_cpt_for_procedure` which are SYNC functions?
        # Let's check original code again.
        pass

    # RE-CHECK Original Code:
    # def _generate_cpt_for_procedure(transcription: str, openai_client, match) -> str:
    #     from app.cpt_mappings import generate_cpt_with_ai
    #     primary, supportive = generate_cpt_with_ai(procedure_text, openai_client)
    
    # In old code `generate_cpt_with_ai` was imported from `cpt_mappings`.
    # I need to check if `cpt_mappings.py` in old code had async or sync `generate_cpt_with_ai`.
    # Based on usage in `_generate_cpt_for_procedure` (which is def, not async def), `generate_cpt_with_ai` must be synchronous there, OR it handles the loop.
    
    # In THIS file (new backend), `generate_cpt_with_ai` is `async def`.
    # If I want to match logic, I should make `_generate_cpt_for_procedure` async and call it directly in gather, OR make `generate_cpt_with_ai` sync.
    
    # EASIER FIX: Make `_generate_cpt_for_procedure` ASYNC.
    # update `validate_and_correct_cpt_codes` to `tasks_to_run.append(generator_func(...))` (without to_thread) if generator_func is async.
    
    return match.group(0) # Placeholder implementation to be replaced below


async def _generate_cpt_for_procedure_async(transcription: str, openai_client, match) -> str:
    """Generate CPT code for a procedure mentioned in transcription - fully AI-driven"""
    procedure_text = _extract_procedure_from_transcription(transcription)
    
    if procedure_text and openai_client:
        primary, supportive = await generate_cpt_with_ai(procedure_text, openai_client)
        if primary:
            return f"{match.group(1)}{primary}{match.group(3)}"
    
    return match.group(0)  # Return original if can't generate


async def _generate_supportive_cpts_async(transcription: str, openai_client, match) -> str:
    """Generate supportive CPT codes - can be multiple codes - fully AI-driven"""
    procedure_text = _extract_procedure_from_transcription(transcription)
    
    if procedure_text and openai_client:
        primary, supportive = await generate_cpt_with_ai(procedure_text, openai_client)
        if supportive and len(supportive) > 0:
            # Format multiple codes as comma-separated string
            codes_str = ", ".join(supportive) if isinstance(supportive, list) else str(supportive)
            return f"{match.group(1)}{codes_str}{match.group(3)}"
    
    return match.group(0)


async def _generate_cpt_for_rfa_async(transcription: str, openai_client, match) -> str:
    """Generate CPT code for RFA section"""
    return await _generate_cpt_for_procedure_async(transcription, openai_client, match)


async def _generate_supportive_cpts_rfa_async(transcription: str, openai_client, match) -> str:
    """Generate supportive CPT codes for RFA section"""
    return await _generate_supportive_cpts_async(transcription, openai_client, match)


# Re-implement validate_and_correct_cpt_codes to use async helpers
async def validate_and_correct_cpt_codes(soap_note: str, transcription: str, openai_client) -> str:
    if not soap_note or not transcription: return soap_note
    if "Not documented" not in soap_note and "[Not documented]" not in soap_note: return soap_note

    result = soap_note
    # Extract procedures/treatments from transcription
    transcription_lower = transcription.lower()
    procedure_keywords = ["injection", "physical therapy", "pt", "mri", "x-ray", "xray", "ct scan", "walking boot", "cam boot", "brace", "crutches", "walker", "cane", "surgery", "arthroscopy", "epidural", "facet", "trigger point", "therapy", "imaging", "procedure", "surgery"]
    if not any(keyword in transcription_lower for keyword in procedure_keywords): return soap_note

    cpt_patterns = [
        (r'(Primary Procedure:\s*\[)(Not documented|\[Not documented\])(\]\s*—\s*\[Procedure Name\])', _generate_cpt_for_procedure_async),
        (r'(Supportive CPTs:\s*\[)(Not documented|\[Not documented\])(\])', _generate_supportive_cpts_async),
        (r'(Primary CPT:\s*\[)(Not documented|\[Not documented\]|Code)(\])', _generate_cpt_for_rfa_async),
        (r'(Supportive CPTs:\s*\[)(Not documented|\[Not documented\]|Codes)(\])', _generate_supportive_cpts_rfa_async),
    ]

    tasks = []
    placeholder_map = {}
    
    for pattern, generator_func in cpt_patterns:
        matches = list(re.finditer(pattern, result, re.IGNORECASE | re.MULTILINE))
        for i, match in enumerate(matches):
            match_text = match.group(0)
            marker = f"__CPT_MARKER_{len(tasks)}__"
            result = result.replace(match_text, marker, 1)
            tasks.append(generator_func(transcription, openai_client, match))
            placeholder_map[marker] = None
    
    if tasks:
        logger.info(f"🚀 Starting parallel CPT generation for {len(tasks)} items...")
        replacements = await asyncio.gather(*tasks)
        for i, marker in enumerate(placeholder_map.keys()):
            result = result.replace(marker, replacements[i])
        logger.info(f"✅ Parallel CPT generation complete")

    return validate_all_cpt_codes_in_soap(result)

def _extract_procedure_from_transcription(transcription: str) -> str:
    """Extract procedure name from transcription using simple heuristics"""
    transcription_lower = transcription.lower()
    procedure_patterns = [
        r"(epidural[^.]*)", r"(injection[^.]*)", r"(physical therapy[^.]*)", r"(\bpt\b[^.]*)",
        r"(mri[^.]*)", r"(x-ray[^.]*)", r"(walking boot[^.]*)", r"(cam boot[^.]*)",
        r"(brace[^.]*)", r"(surgery[^.]*)", r"(arthroscopy[^.]*)"
    ]
    for pattern in procedure_patterns:
        match = re.search(pattern, transcription_lower, re.IGNORECASE)
        if match: return match.group(1).strip()
    return transcription[:200] if len(transcription) > 200 else transcription

# Stub for compatibility with previous function names if needed
def _generate_cpt_for_procedure(*args, **kwargs): pass
def _generate_supportive_cpts(*args, **kwargs): pass
def _generate_cpt_for_rfa(*args, **kwargs): pass
def _generate_supportive_cpts_rfa(*args, **kwargs): pass

