"""
CPT/HCPCS Code Generation for Orthopedic Procedures
All CPT codes are generated dynamically using AI (GPT-5.1) via API calls.
NO static code lists or hardcoded mappings - everything is AI-generated.
"""
import os

# 🔴 CRITICAL: All CPT codes are generated dynamically using GPT-5.1 API calls
# NO static mappings - NO hardcoded codes - Everything is AI-generated
# The AI uses its comprehensive medical coding knowledge to generate all applicable codes


def get_e_m_code(visit_type: str, complexity: str) -> tuple:
    """
    Get E/M code based on visit type and complexity.
    Static mappings removed - E/M codes should be extracted from transcription using AI.
    Returns (code, description) or (None, None).
    """
    # Static mappings removed - E/M codes should be extracted from transcription
    return (None, None)


def is_valid_cpt_code(code: str) -> bool:
    """
    Validate if a code is a valid CPT or HCPCS code.
    STRICT VALIDATION - Only accepts properly formatted codes.
    
    CPT codes: Exactly 5 digits (e.g., 29881, 20610)
    HCPCS codes: Letter(s) followed by digits (e.g., L1833, E0114, A4566, C1713)
    
    Returns:
        True if valid, False otherwise
    """
    if not code:
        return False
    
    code_str = str(code).strip()
    
    # Remove any dashes, spaces, dots, or modifiers
    # Handle codes with modifiers like "29888-RT" - extract base code
    if "-" in code_str:
        # Split on dash and take first part (base code)
        code_str = code_str.split("-")[0].strip()
    code_str = code_str.replace(" ", "").replace(".", "").replace("/", "")
    
    # Empty after cleaning
    if not code_str:
        return False
    
    # Reject codes that are too short or too long
    if len(code_str) < 4 or len(code_str) > 5:
        return False
    
    # Reject codes that contain invalid characters
    # Should only contain letters and digits
    if not code_str.replace(" ", "").isalnum():
        return False
    
    # CPT codes: Exactly 5 digits (numeric only)
    if len(code_str) == 5:
        if code_str.isdigit():
            # Valid CPT code (5 digits)
            return True
        # HCPCS codes: Letter(s) followed by digits, total length 5
        if code_str[0].isalpha():
            # Single letter + 4 digits (most common: L1833, E0114, A4566, C1713)
            if len(code_str) == 5 and code_str[1:].isdigit():
                return True
            # Two letters + 3 digits (e.g., Q4001, WC002)
            if len(code_str) >= 2 and code_str[0:2].isalpha() and len(code_str) == 5 and code_str[2:].isdigit():
                return True
    
    # HCPCS codes: 4 characters (less common but valid)
    # Single letter + 3 digits
    if len(code_str) == 4:
        if code_str[0].isalpha() and code_str[1:].isdigit():
            return True
    
    # If we get here, code doesn't match any valid format
    return False


def generate_cpt_with_ai(procedure_description: str, openai_client=None) -> tuple:
    """
    Use AI (GPT-5.1) to GENERATE comprehensive CPT/HCPCS codes dynamically.
    NO static code lists - all codes are generated by AI based on procedure/service description.
    Returns (primary_cpt, supportive_cpts_list) or (None, []) if unable to generate.
    
    This function makes API calls to GPT-5.1 to generate ALL possible codes dynamically.
    """
    if not procedure_description or not procedure_description.strip():
        return (None, [])
    
    if not openai_client:
        try:
            # Try to import from main or pr1_generator
            try:
                from app.main import create_openai_client
            except ImportError:
                from app.api.pr1_generator import create_openai_client
            openai_client = create_openai_client()
        except Exception:
            return (None, [])
    
    try:
        system_prompt = """You are a medical coding expert specializing in CPT and HCPCS codes for orthopedic procedures, surgeries, and services.

🔴 CRITICAL: Generate ALL applicable CPT (5-digit numeric) AND HCPCS (Letter + 4 digits) codes.
🔴 CRITICAL: Generate codes for ALL ordered services: Surgeries, Injections, Imaging, Therapy (PT/OT), DME, Supplies, etc.
🔴 CRITICAL: You MUST GENERATE ALL POSSIBLE CODES for Workers' Compensation RFA authorization.
🔴 DO NOT extract only what is mentioned - GENERATE ALL POSSIBLE CODES that could apply for the procedure/service.
🔴 Your goal is MAXIMUM code inclusion for comprehensive authorization coverage.

Your task is to GENERATE COMPREHENSIVE CODING for the PROCEDURE/SERVICE mentioned in the transcription.

🔴 CRITICAL VALIDATION RULES - 100% VALID CODES ONLY:
YOU MUST GENERATE ONLY VALID CPT OR HCPCS CODES - NO INVALID CODES ALLOWED

VALID CODE FORMATS (ONLY THESE ARE ACCEPTED):
1. CPT Codes: Exactly 5 digits, numeric only (e.g., 29881, 20610, 97110, 73721)
2. HCPCS Codes: Single letter followed by 4 digits (e.g., L1832, E0114, J1040, A4566)
   - Range: A0000-V9999
   - Common prefixes: L (DME), E (DME), J (Drugs), A (Supplies), C (Implants)

INVALID CODE FORMATS (DO NOT GENERATE THESE):
❌ Codes with 3 digits or less (e.g., 298, 88)
❌ Codes with 6+ digits (e.g., 298881, 123456)
❌ Codes with special characters (e.g., 298-81, 298.81) - except modifiers like -RT, -LT
❌ Placeholder codes (e.g., "XXXXX", "CODE", "TBD")

CRITICAL RULES - GENERATE ALL POSSIBLE VALID CODES:
1. Identify the PROCEDURE/SERVICE mentioned in the transcription (Surgery, Injection, DME, PT, MRI, etc.)
2. Generate the PRIMARY code for the main service (MUST BE VALID FORMAT)
3. Generate ALL SUPPORTIVE codes that could apply (ALL MUST BE VALID FORMAT):
   - Surgical procedures: Surgical CPTs, Implants (C/L codes), Grafts, Supplies
   - Injections: Injection CPTs, Drug HCPCS (J-codes), Guidance (7xxxx), Supplies
   - DME: Product HCPCS (L/E codes), Adjustment/Fitting codes
   - PT/OT: Evaluation (9716x), Therapeutic specific codes (97110, 97140, etc.)
   - Imaging: Primary CPT (7xxxx)
4. MANDATORY: Generate ALL POSSIBLE codes for the service
5. MANDATORY: EVERY CODE MUST BE VALID FORMAT - verify before including
6. Think comprehensively - include ALL codes that could be part of the authorization
7. DO NOT limit yourself - generate ALL possible codes
8. DO NOT stop at 6-8 codes - continue until you have ALL possible codes

Return a JSON object with:
{
  "primary_cpt": "CODE" or null,
  "supportive_cpts": ["CODE1", "CODE2", "CODE3", ...] (ALL possible comprehensive codes generated by AI),
  "description": "Brief description"
}

🔴 CRITICAL: Generate ALL possible codes dynamically using your medical coding knowledge.
🔴 DO NOT use static code lists - generate codes based on the procedure/service described.
🔴 Use GPT-5.1's comprehensive medical coding knowledge to generate all applicable codes.

If no procedure is mentioned, return:
{
  "primary_cpt": null,
  "supportive_cpts": [],
  "description": null
}"""

        user_prompt = f"""Generate COMPREHENSIVE CPT/HCPCS codes for this procedure/service:

{procedure_description}

🔴 CRITICAL - GENERATE ALL POSSIBLE VALID CODES:
🔴 100% VALID CODES REQUIRED - NO INVALID CODES ALLOWED
🔴 INCLUDE HCPCS CODES (DME, Drugs, Supplies) IF APPLICABLE

VALID CODE FORMATS (ONLY GENERATE THESE):
✓ CPT Codes: Exactly 5 digits, numeric only (e.g., 29881, 97110)
✓ HCPCS Codes: Letter + 4 digits (e.g., L1832, J1040)

INVALID FORMATS (DO NOT GENERATE):
✗ Codes with wrong length (3 digits, 6+ digits)
✗ Codes with letters in wrong position (unless valid HCPCS)
✗ Codes with special characters
✗ Placeholder codes

VALIDATION CHECKLIST - Before including each code:
□ Is it exactly 5 digits numeric OR Letter+4 digits?
□ Is it a real, valid CPT or HCPCS code?
□ If NO to any → DO NOT include that code

- FIRST: Identify the procedure/service (Surgery, Injection, DME, PT, etc.)
- Generate the PRIMARY code
- Generate ALL SUPPORTIVE codes (Surgical, Implants, Grafts, Drugs, Supplies, DME, Therapy)
- MANDATORY: Generate ALL POSSIBLE codes
- MANDATORY: EVERY CODE MUST BE VALID - verify format before including
- Think comprehensively - include ALL codes that could be part of the authorization
- DO NOT limit yourself - generate ALL possible codes
- DO NOT stop at 6-8 codes - continue until you have ALL possible codes
- FINAL CHECK: Verify ALL codes are valid format before returning

**CODE GENERATION CHECKLIST:**
For Surgery: Primary CPT, Related CPTs, Implants (C/L), Grafts, Supplies (A/Q), DME (L/E)
For Injections: Injection CPT, Drug J-codes, Guidance CPT, Supplies
For DME: Base L-code, Add-on L-codes
For PT/OT: Eval codes, Treatment codes (97xxx)
For Imaging: MRI/CT/X-ray CPTs

Return the JSON object with ALL possible comprehensive codes."""

        response = openai_client.chat.completions.create(
            model='gpt-4o',  # Use GPT-4o model
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ],
            temperature=0.2,  # Slightly higher to encourage comprehensive code generation
            response_format={"type": "json_object"},
            max_completion_tokens=8000  # Increased to allow 60+ codes with descriptions in response
        )
        
        result = response.choices[0].message.content
        import json
        import logging
        logger = logging.getLogger(__name__)
        data = json.loads(result)
        
        primary = data.get("primary_cpt")
        supportive = data.get("supportive_cpts", [])
        
        # Validate and filter codes
        validated_primary = None
        if primary:
            primary_str = str(primary).strip()
            if is_valid_cpt_code(primary_str):
                validated_primary = primary_str
            else:
                logger.warning(f"Invalid primary CPT code filtered out: {primary_str}")
        
        # Validate supportive codes
        validated_supportive = []
        if isinstance(supportive, list):
            for code in supportive:
                if code:
                    code_str = str(code).strip()
                    if is_valid_cpt_code(code_str):
                        # Avoid duplicates
                        if code_str not in validated_supportive:
                            validated_supportive.append(code_str)
                    else:
                        logger.warning(f"Invalid supportive CPT code filtered out: {code_str}")
        
        if validated_primary:
            logger.info(f"Generated {len(validated_supportive)} valid supportive CPT codes")
            return (validated_primary, validated_supportive)
        
        return (None, [])
        
    except Exception as e:
        # Log error but don't fail
        import logging
        logger = logging.getLogger(__name__)
        logger.warning(f"Error generating CPT code with AI: {e}")
        return (None, [])


def validate_cpt_codes_relevance(cpt_codes: list, transcription: str, openai_client=None) -> list:
    """
    Validate that CPT codes are actually relevant to the transcription.
    Filters out codes that are not related to procedures/services mentioned in transcription.
    
    Args:
        cpt_codes: List of CPT codes to validate
        transcription: The transcription text to check relevance against
        openai_client: Optional OpenAI client
    
    Returns:
        List of CPT codes that are relevant to the transcription
    """
    if not cpt_codes or not transcription:
        return []
    
    if not openai_client:
        try:
            try:
                from app.main import create_openai_client
            except ImportError:
                from app.api.pr1_generator import create_openai_client
            openai_client = create_openai_client()
        except Exception:
            return cpt_codes  # Return as-is if can't validate
    
    try:
        import json
        import logging
        logger = logging.getLogger(__name__)
        
        # Limit transcription length
        transcription_snippet = str(transcription)[:3000] if len(str(transcription)) > 3000 else str(transcription)
        
        system_prompt = """You are a medical coding validation expert. Your task is to validate if CPT/HCPCS codes are relevant to the procedures/services mentioned in a medical transcription.

🔴 CRITICAL: For Workers' Compensation RFA, comprehensive code inclusion is standard practice.
🔴 BE PERMISSIVE - Include codes that could reasonably apply to the procedure/service.

CRITICAL VALIDATION RULES - BE PERMISSIVE FOR RFA AUTHORIZATION:
1. FIRST: Identify the PRIMARY PROCEDURE/SERVICE from the transcription (e.g., "ACL reconstruction", "knee surgery", "injection", "MRI", "PT", "brace", etc.)

2. A code is RELEVANT if ANY of the following are true:
   - The procedure/service it represents is mentioned in the transcription
   - The code is for a related procedure/service that could be part of the authorization
   - The code is for the same body part as the procedure (e.g., knee procedure → knee codes are relevant)
   - The code is for standard components of the procedure (e.g., surgery → surgical codes, graft codes, DME codes, PT codes, supply codes)
   - The code is for DME/supplies that could be needed for the procedure
   - The code is for imaging that could be needed for the procedure
   - The code is for post-operative care related to the procedure

3. A code is NOT RELEVANT ONLY if:
   - The code is for a completely unrelated body part (e.g., knee procedure → shoulder codes are NOT relevant)
   - The code is for a completely unrelated condition (e.g., ACL surgery → rotator cuff codes are NOT relevant)
   - The code is clearly not part of the procedure/service mentioned

4. Be PERMISSIVE - mark codes as relevant if they:
   - Could reasonably be part of the procedure/service
   - Are for the same body part
   - Are standard components of the procedure type
   - Could be needed for authorization

Return a JSON object with:
{
  "relevant_codes": ["CODE1", "CODE2", ...] (only codes that are actually relevant),
  "irrelevant_codes": ["CODE3", "CODE4", ...] (codes that are not relevant)
}"""

        user_prompt = f"""Validate if these CPT/HCPCS codes are relevant to the procedure/service mentioned in this transcription:

CPT Codes to validate:
{', '.join(cpt_codes[:100])}  # Increased limit to 100 codes

Transcription:
{transcription_snippet}

🔴 CRITICAL - BE PERMISSIVE FOR RFA AUTHORIZATION:
FIRST: Identify the PRIMARY PROCEDURE/SERVICE from the transcription (e.g., "ACL reconstruction", "knee surgery", "injection", "MRI", "PT", "brace", etc.)

For EACH code, verify:
1. Is this code for the same body part as the procedure? (e.g., knee procedure → knee codes are relevant)
2. Is this code a standard component of this procedure type? (e.g., surgery → surgical codes, graft codes, DME codes are relevant)
3. Could this code be needed for authorization of this procedure? (e.g., surgery → post-op DME, PT, supplies are relevant)
4. If ANY answer is YES, mark the code as RELEVANT

- Mark codes as relevant if they:
  * Are for the same body part as the procedure
  * Are standard components of the procedure type
  * Could reasonably be part of the authorization
  * Are for related services (DME, PT, imaging, supplies) that could be needed
- **CRITICAL:** DO NOT include imaging codes (MRI, X-ray, CT, etc.) unless they are explicitly mentioned as being ordered or needed in the transcription. Even if it's for the same body part, if the doctor didn't explicitly mention imaging, do not include it.
- **CRITICAL:** Mentions of imaging results (e.g., "MRI shows tear") are NOT orders and should NOT result in inclusion of imaging CPT codes.
- Only filter out codes that are clearly for unrelated body parts or conditions.

Return the JSON object with relevant and irrelevant codes. Be permissive - include most codes that could apply."""

        response = openai_client.chat.completions.create(
            model='gpt-4o',  # Use gpt-4o for validation
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt}
            ],
            temperature=0.2,  # Slightly higher to be more permissive
            response_format={"type": "json_object"},
            max_completion_tokens=4000  # Increased to allow validation of more codes
        )
        
        result = response.choices[0].message.content
        data = json.loads(result)
        
        relevant_codes = data.get("relevant_codes", [])
        
        # Validate codes are actually valid CPT codes
        validated_relevant = []
        for code in relevant_codes:
            code_str = str(code).strip()
            if is_valid_cpt_code(code_str) and code_str in cpt_codes:
                validated_relevant.append(code_str)
        
        filtered_count = len(cpt_codes) - len(validated_relevant)
        if filtered_count > 0:
            logger.info(f"Filtered out {filtered_count} irrelevant CPT codes. Kept {len(validated_relevant)} relevant codes.")
        
        return validated_relevant
        
    except Exception as e:
        import logging
        logger = logging.getLogger(__name__)
        logger.warning(f"Error validating CPT codes relevance: {e}")
        return cpt_codes  # Return as-is if validation fails


def get_cpt_for_procedure_enhanced(procedure_text: str, openai_client=None) -> tuple:
    """
    Extract CPT codes using AI only (static mappings removed).
    This makes the system fully dynamic - extracts codes from transcription.
    Returns (primary_cpt, supportive_cpts_list)
    """
    # Use AI to extract codes from transcription (no static mappings)
    return generate_cpt_with_ai(procedure_text, openai_client)
