"""
Prompts and terminology corrections for medical transcription
"""

# Medical terminology corrections
MEDICAL_TERMINOLOGY_CORRECTIONS = {
    "false lip trauma": "fall slip trauma",
    "catching lock": "catching, locking",
    "open condition": "open skin lesion",
    "no regrowth": "no regressed",
    "trichomobarbital": "tricompartmental",
    "lacking": "locking",
    "lip trauma": "slip trauma",
    "10derness": "tenderness",
    "10der": "tender",
    "medial joint line 10derness": "medial joint line tenderness",
    "anterior medial aspect": "anteromedial aspect",
    "turner": "terminal",
    "contra when": "contralateral",
}


# ============================================
# ORTHOPEDIC SOAP NOTE GENERATION PROMPT
# ============================================

ORTHOPEDIC_SOAP_SYSTEM_PROMPT = """You are an expert medical documentation AI assistant specializing in orthopedic consultation notes. Your task is to transform clinical transcriptions into structured, professional SOAP notes that comply with DWC, AMA, and HIPAA documentation standards.

You must follow the ORTHOPEDIC CONSULTATION SOAP NOTE TEMPLATE format exactly."""


ORTHOPEDIC_SOAP_USER_PROMPT_TEMPLATE = """Transform the following clinical transcription into a comprehensive, structured SOAP note following the orthopedic consultation format.

**TRANSCRIPTION:**
{transcription}

{patient_context}

**INSTRUCTIONS:**
1. Correct any grammatical or typographical errors while preserving clinical meaning
2. Organize information into the structured SOAP format below
3. Extract and include ICD-10 codes for diagnoses when possible
4. Use professional orthopedic terminology
5. Do NOT invent information not present in the transcription
6. If information for a section is not available, note as "[Not documented]"
7. Format the output in clean Markdown

**REQUIRED FORMAT (Markdown):**

# 📝 ORTHOPEDIC CONSULTATION – SOAP NOTE

{header_section}

---

## S – SUBJECTIVE

### Chief Complaint
[Primary symptom or reason for visit from transcription]

### History of Present Illness
[Detailed description from transcription — onset, mechanism of injury, pain level, progression, and current status]

### Past Medical History
[List key comorbidities – e.g., HTN, AFib, DM, etc. or "None documented"]

### Medications
[List medications or note "As per chart" or "None documented"]

### Social History
[Living situation, independence, work, assistive devices, etc. or "Not documented"]

### Review of Systems
[Positive and negative symptoms relevant to the injury or "Not documented"]

---

## O – OBJECTIVE

### General Exam
[Patient appearance, distress level, vitals if mentioned]

### Local Exam
- **Inspection:** [Swelling, deformity, wound, etc.]
- **Palpation:** [Tenderness sites, warmth, etc.]
- **ROM:** [Limitations, pain, inability to move, etc.]
- **Neurovascular:** [Sensory/motor intactness, pulses]

### Imaging
[X-ray/MRI/CT findings summarized or "Not performed"]

---

## A – ASSESSMENT

| Condition | ICD-10 Code | Notes |
|-----------|-------------|-------|
| [Primary Diagnosis] | [ICD-10] | [Brief notes] |
| [Secondary Diagnosis if any] | [ICD-10] | [Brief notes] |
| [Mechanism/Associated condition] | [ICD-10] | [e.g., Fall mechanism] |

---

## P – PLAN

### Immediate Treatment
- [Casting, splinting, surgical planning, medication, etc.]

### Follow-Up Instructions
- [Recheck timing, repeat imaging, cast removal, transition to brace, etc.]

### Surgical Plan (if applicable)
- [Procedure, timing, consent obtained, labs, NPO status, pre-op clearance]

### Patient Education
- [Precautions, expected recovery timeline, signs to watch for]

### Work Status (if applicable)
[Return to work status and restrictions]

### RFA/Authorization (if applicable)
[Any authorization requests needed]

---

**✅ Generated by Ortho AI Voice Charting** (Whisper → SOAP → ICD-10 Mapping)  
*Compliant with DWC, AMA, and HIPAA documentation standards.*

---

Please generate the SOAP note following this exact Markdown format, with clear sections and professional medical language."""

