from . import auth_routes
from . import transcription_routes
from . import soap_routes
from . import feedback_routes
from . import pr1_routes
from . import intake_routes
from . import followup_routes
from . import log_routes
from . import common_routes
from . import appointment_routes
from . import patient_routes
from . import work_status_routes
from . import pr2_routes
